from . import res_partner
from . import account_move
from . import account_payment
from . import stock_move
from . import stock_picking
from . import base_model
from . import res_config_settings
from . import product_pricelist
from . import sale_order
