{
    "name": "Counter Sale Imporpalac",
    "category": "Sales/Sales",
    "version": "17.0.1.0.0",
    "author": "Santiago Illapa / FenixERP",
    "summary": "This module is used for the sales flow at the counter",
    "depends": [
        "sale_management",
        "account",
        "stock",
        "payment_type",
        "sale_order_payment",
        "stock_picking_flow",
        "sale_order_ticket",
        "bi_so_po_catalog_view",
        "qz_tray_printer",
        "post_dated_cheque_management_knk",
        "sale_info_additional",
        "base_accounting_kit",
        "sale_stock",
        "price_list_line",
        "l10n_ec_imports",
    ],
    "data": [
        "security/counter_sale_security.xml",
        "data/expire_quotation_cron.xml",
        "data/ir_config_parameter.xml",
        "views/sale_order_inherit.xml",
        "views/account_move_inherit.xml",
        "views/stock_move_inherit.xml",
        "views/stock_picking_inherit.xml",
        "views/stock_picking_multicomp_view.xml",
        "views/account_payment_inherit.xml",
        "views/view_res_config_setting.xml",
        "views/imports_inherit.xml",
        "wizards/sale_order_cancel_wizard_view.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "counter_sale/static/src/js/confirm_btn_controller.js",
            "counter_sale/static/src/js/tree_view_refresh.js",
        ],
    },
    "demo": [],
    "website": "https://github.com/Fenix-ERP/l10n-ecuador",
    "license": "LGPL-3",
}
