{
    "name": "Additional Fields Imporpalac",
    "version": "17.0.0.0.1",
    "category": "stock",
    "summary": "Fields Additional Products Imporpalac",
    "author": "Jorge Armas / FenixERP",
    "website": "https://github.com/Fenix-ERP/l10n-ecuador",
    "depends": ["stock", "l10n_ec_purchase_reception", "account", "stock_picking_flow"],
    "data": [
        "security/hide_product_price_cost_groups.xml",
        "views/additional_product_inherit_view.xml",
        "views/account_evoucher_update_view.xml",
        "views/sale_order_time_view.xml",
        "views/account_homologate_inherit_view.xml",
        "views/stock_picking_inherit_view.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
    ],
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "OPL-1",
    "external_dependencies": {"python": ["openpyxl"]},
}
